// Comprehensive list of world currencies with ISO 4217 code, genuine symbol, flag emoji, and name
class AppCurrencies {
  static const List<Map<String, String>> all = [
    {'code': 'USD', 'symbol': '\$', 'name': 'US Dollar', 'flag': '🇺🇸'},
    {'code': 'EUR', 'symbol': '€', 'name': 'Euro', 'flag': '🇪🇺'},
    {'code': 'GBP', 'symbol': '£', 'name': 'British Pound', 'flag': '🇬🇧'},
    {'code': 'PKR', 'symbol': '₨', 'name': 'Pakistani Rupee', 'flag': '🇵🇰'},
    {'code': 'INR', 'symbol': '₹', 'name': 'Indian Rupee', 'flag': '🇮🇳'},
    {'code': 'AED', 'symbol': 'د.إ', 'name': 'UAE Dirham', 'flag': '🇦🇪'},
    {'code': 'SAR', 'symbol': '﷼', 'name': 'Saudi Riyal', 'flag': '🇸🇦'},
    {'code': 'CAD', 'symbol': 'CA\$', 'name': 'Canadian Dollar', 'flag': '🇨🇦'},
    {'code': 'AUD', 'symbol': 'AU\$', 'name': 'Australian Dollar', 'flag': '🇦🇺'},
    {'code': 'JPY', 'symbol': '¥', 'name': 'Japanese Yen', 'flag': '🇯🇵'},
    {'code': 'CNY', 'symbol': '¥', 'name': 'Chinese Yuan', 'flag': '🇨🇳'},
    {'code': 'SGD', 'symbol': 'S\$', 'name': 'Singapore Dollar', 'flag': '🇸🇬'},
    {'code': 'BDT', 'symbol': '৳', 'name': 'Bangladeshi Taka', 'flag': '🇧🇩'},
    {'code': 'CHF', 'symbol': 'CHF', 'name': 'Swiss Franc', 'flag': '🇨🇭'},
    {'code': 'MYR', 'symbol': 'RM', 'name': 'Malaysian Ringgit', 'flag': '🇲🇾'},
    {'code': 'TRY', 'symbol': '₺', 'name': 'Turkish Lira', 'flag': '🇹🇷'},
    {'code': 'RUB', 'symbol': '₽', 'name': 'Russian Ruble', 'flag': '🇷🇺'},
    {'code': 'BRL', 'symbol': 'R\$', 'name': 'Brazilian Real', 'flag': '🇧🇷'},
    {'code': 'KRW', 'symbol': '₩', 'name': 'South Korean Won', 'flag': '🇰🇷'},
    {'code': 'ZAR', 'symbol': 'R', 'name': 'South African Rand', 'flag': '🇿🇦'},
    {'code': 'MXN', 'symbol': 'Mex\$', 'name': 'Mexican Peso', 'flag': '🇲🇽'},
    {'code': 'IDR', 'symbol': 'Rp', 'name': 'Indonesian Rupiah', 'flag': '🇮🇩'},
    {'code': 'PHP', 'symbol': '₱', 'name': 'Philippine Peso', 'flag': '🇵🇭'},
    {'code': 'THB', 'symbol': '฿', 'name': 'Thai Baht', 'flag': '🇹🇭'},
    {'code': 'VND', 'symbol': '₫', 'name': 'Vietnamese Dong', 'flag': '🇻🇳'},
    {'code': 'EGP', 'symbol': 'E£', 'name': 'Egyptian Pound', 'flag': '🇪🇬'},
    {'code': 'QAR', 'symbol': 'ر.ق', 'name': 'Qatari Riyal', 'flag': '🇶🇦'},
    {'code': 'KWD', 'symbol': 'د.ك', 'name': 'Kuwaiti Dinar', 'flag': '🇰🇼'},
    {'code': 'OMR', 'symbol': 'ر.ع.', 'name': 'Omani Rial', 'flag': '🇴🇲'},
    {'code': 'BHD', 'symbol': '.د.ب', 'name': 'Bahraini Dinar', 'flag': '🇧🇭'},
    {'code': 'NZD', 'symbol': 'NZ\$', 'name': 'New Zealand Dollar', 'flag': '🇳🇿'},
    {'code': 'HKD', 'symbol': 'HK\$', 'name': 'Hong Kong Dollar', 'flag': '🇭🇰'},
    {'code': 'SEK', 'symbol': 'kr', 'name': 'Swedish Krona', 'flag': '🇸🇪'},
    {'code': 'NOK', 'symbol': 'kr', 'name': 'Norwegian Krone', 'flag': '🇳🇴'},
    {'code': 'DKK', 'symbol': 'kr.', 'name': 'Danish Krone', 'flag': '🇩🇰'},
    {'code': 'PLN', 'symbol': 'zł', 'name': 'Polish Zloty', 'flag': '🇵🇱'},
    {'code': 'CZK', 'symbol': 'Kč', 'name': 'Czech Koruna', 'flag': '🇨🇿'},
    {'code': 'HUF', 'symbol': 'Ft', 'name': 'Hungarian Forint', 'flag': '🇭🇺'},
    {'code': 'RON', 'symbol': 'lei', 'name': 'Romanian Leu', 'flag': '🇷🇴'},
    {'code': 'ILS', 'symbol': '₪', 'name': 'Israeli New Shekel', 'flag': '🇮🇱'},
    {'code': 'CLP', 'symbol': 'CL\$', 'name': 'Chilean Peso', 'flag': '🇨🇱'},
    {'code': 'COP', 'symbol': 'COL\$', 'name': 'Colombian Peso', 'flag': '🇨🇴'},
    {'code': 'ARS', 'symbol': 'AR\$', 'name': 'Argentine Peso', 'flag': '🇦🇷'},
    {'code': 'PEN', 'symbol': 'S/.', 'name': 'Peruvian Sol', 'flag': '🇵🇪'},
    {'code': 'NGN', 'symbol': '₦', 'name': 'Nigerian Naira', 'flag': '🇳🇬'},
    {'code': 'KES', 'symbol': 'KSh', 'name': 'Kenyan Shilling', 'flag': '🇰🇪'},
    {'code': 'GHS', 'symbol': '₵', 'name': 'Ghanaian Cedi', 'flag': '🇬🇭'},
    {'code': 'LKR', 'symbol': 'Rs', 'name': 'Sri Lankan Rupee', 'flag': '🇱🇰'},
    {'code': 'NPR', 'symbol': 'रू', 'name': 'Nepalese Rupee', 'flag': '🇳🇵'},
    {'code': 'AFN', 'symbol': '؋', 'name': 'Afghan Afghani', 'flag': '🇦🇫'},
    {'code': 'ALL', 'symbol': 'L', 'name': 'Albanian Lek', 'flag': '🇦🇱'},
    {'code': 'DZD', 'symbol': 'د.ج', 'name': 'Algerian Dinar', 'flag': '🇩🇿'},
    {'code': 'AOA', 'symbol': 'Kz', 'name': 'Angolan Kwanza', 'flag': '🇦🇴'},
    {'code': 'AMD', 'symbol': '֏', 'name': 'Armenian Dram', 'flag': '🇦🇲'},
    {'code': 'AWG', 'symbol': 'ƒ', 'name': 'Aruban Florin', 'flag': '🇦🇼'},
    {'code': 'AZN', 'symbol': '₼', 'name': 'Azerbaijani Manat', 'flag': '🇦🇿'},
    {'code': 'BSD', 'symbol': 'B\$', 'name': 'Bahamian Dollar', 'flag': '🇧🇸'},
    {'code': 'BBD', 'symbol': 'Bds\$', 'name': 'Barbadian Dollar', 'flag': '🇧🇧'},
    {'code': 'BYN', 'symbol': 'Br', 'name': 'Belarusian Ruble', 'flag': '🇧🇾'},
    {'code': 'BZD', 'symbol': 'BZ\$', 'name': 'Belize Dollar', 'flag': '🇧🇿'},
    {'code': 'BMD', 'symbol': 'BD\$', 'name': 'Bermudan Dollar', 'flag': '🇧🇲'},
    {'code': 'BTN', 'symbol': 'Nu.', 'name': 'Bhutanese Ngultrum', 'flag': '🇧🇹'},
    {'code': 'BOB', 'symbol': 'Bs.', 'name': 'Bolivian Boliviano', 'flag': '🇧🇴'},
    {'code': 'BAM', 'symbol': 'KM', 'name': 'Bosnia-Herzegovina Mark', 'flag': '🇧🇦'},
    {'code': 'BWP', 'symbol': 'P', 'name': 'Botswanan Pula', 'flag': '🇧🇼'},
    {'code': 'BND', 'symbol': 'B\$', 'name': 'Brunei Dollar', 'flag': '🇧🇳'},
    {'code': 'BGN', 'symbol': 'лв', 'name': 'Bulgarian Lev', 'flag': '🇧🇬'},
    {'code': 'BIF', 'symbol': 'FBu', 'name': 'Burundian Franc', 'flag': '🇧🇮'},
    {'code': 'KHR', 'symbol': '៛', 'name': 'Cambodian Riel', 'flag': '🇰🇭'},
    {'code': 'CVE', 'symbol': 'Esc', 'name': 'Cape Verdean Escudo', 'flag': '🇨🇻'},
    {'code': 'KYD', 'symbol': 'CI\$', 'name': 'Cayman Islands Dollar', 'flag': '🇰🇾'},
    {'code': 'XAF', 'symbol': 'FCFA', 'name': 'Central African CFA Franc', 'flag': '🇨🇲'},
    {'code': 'XPF', 'symbol': 'CFPF', 'name': 'CFP Franc', 'flag': '🇵🇫'},
    {'code': 'CRC', 'symbol': '₡', 'name': 'Costa Rican Colon', 'flag': '🇨🇷'},
    {'code': 'DOP', 'symbol': 'RD\$', 'name': 'Dominican Peso', 'flag': '🇩🇴'},
    {'code': 'FJD', 'symbol': 'FJ\$', 'name': 'Fijian Dollar', 'flag': '🇫🇯'},
    {'code': 'GEL', 'symbol': '₾', 'name': 'Georgian Lari', 'flag': '🇬🇪'},
    {'code': 'GIP', 'symbol': '£', 'name': 'Gibraltar Pound', 'flag': '🇬🇮'},
    {'code': 'GTQ', 'symbol': 'Q', 'name': 'Guatemalan Quetzal', 'flag': '🇬🇹'},
    {'code': 'GYD', 'symbol': 'GY\$', 'name': 'Guyanaese Dollar', 'flag': '🇬🇾'},
    {'code': 'HNL', 'symbol': 'L', 'name': 'Honduran Lempira', 'flag': '🇭🇳'},
    {'code': 'ISK', 'symbol': 'kr', 'name': 'Icelandic Krona', 'flag': '🇮🇸'},
    {'code': 'IQD', 'symbol': 'ع.د', 'name': 'Iraqi Dinar', 'flag': '🇮🇶'},
    {'code': 'JMD', 'symbol': 'J\$', 'name': 'Jamaican Dollar', 'flag': '🇯🇲'},
    {'code': 'JOD', 'symbol': 'د.ا', 'name': 'Jordanian Dinar', 'flag': '🇯🇴'},
    {'code': 'KZT', 'symbol': '₸', 'name': 'Kazakhstani Tenge', 'flag': '🇰🇿'},
    {'code': 'KGS', 'symbol': 'с', 'name': 'Kyrgystani Som', 'flag': '🇰🇬'},
    {'code': 'LAK', 'symbol': '₭', 'name': 'Laotian Kip', 'flag': '🇱🇦'},
    {'code': 'LBP', 'symbol': 'ل.ل', 'name': 'Lebanese Pound', 'flag': '🇱🇧'},
    {'code': 'MAD', 'symbol': 'د.م.', 'name': 'Moroccan Dirham', 'flag': '🇲🇦'},
    {'code': 'MNT', 'symbol': '₮', 'name': 'Mongolian Tugrik', 'flag': '🇲🇳'},
    {'code': 'MZN', 'symbol': 'MT', 'name': 'Mozambican Metical', 'flag': '🇲🇿'},
    {'code': 'MMK', 'symbol': 'K', 'name': 'Myanmar Kyat', 'flag': '🇲🇲'},
    {'code': 'NAD', 'symbol': 'N\$', 'name': 'Namibian Dollar', 'flag': '🇳🇦'},
    {'code': 'NIO', 'symbol': 'C\$', 'name': 'Nicaraguan Cordoba', 'flag': '🇳🇮'},
    {'code': 'PAB', 'symbol': 'B/.', 'name': 'Panamanian Balboa', 'flag': '🇵🇦'},
    {'code': 'PGK', 'symbol': 'K', 'name': 'Papua New Guinean Kina', 'flag': '🇵🇬'},
    {'code': 'PYG', 'symbol': '₲', 'name': 'Paraguayan Guarani', 'flag': '🇵🇾'},
    {'code': 'RWF', 'symbol': 'RF', 'name': 'Rwandan Franc', 'flag': '🇷🇼'},
    {'code': 'RSD', 'symbol': 'дин.', 'name': 'Serbian Dinar', 'flag': '🇷🇸'},
    {'code': 'TZS', 'symbol': 'TSh', 'name': 'Tanzanian Shilling', 'flag': '🇹🇿'},
    {'code': 'TTD', 'symbol': 'TT\$', 'name': 'Trinidad and Tobago Dollar', 'flag': '🇹🇹'},
    {'code': 'TND', 'symbol': 'د.ت', 'name': 'Tunisian Dinar', 'flag': '🇹🇳'},
    {'code': 'UGX', 'symbol': 'USh', 'name': 'Ugandan Shilling', 'flag': '🇺🇬'},
    {'code': 'UAH', 'symbol': '₴', 'name': 'Ukrainian Hryvnia', 'flag': '🇺🇦'},
    {'code': 'UYU', 'symbol': '\$U', 'name': 'Uruguayan Peso', 'flag': '🇺🇾'},
    {'code': 'UZS', 'symbol': 'soʻm', 'name': 'Uzbekistani Som', 'flag': '🇺🇿'},
    {'code': 'VES', 'symbol': 'Bs.S', 'name': 'Venezuelan Bolivar', 'flag': '🇻🇪'},
    {'code': 'ZMW', 'symbol': 'ZK', 'name': 'Zambian Kwacha', 'flag': '🇿🇲'},
  ];
}
